In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
orders = pd.read_csv("Orders_dataset.csv")
orders.head(5)

,order_id,customer_name,product,category,quantity,amount,region,order_date,status
0,1001,Chidi Okafor,Laptop,Electronics,2,360000,South,1/5/2024,Delivered
1,1002,Amina Bello,Phone,Electronics,1,85000,North,1/7/2024,Delivered
2,1003,Tunde Adeyemi,Tablet,Electronics,3,210000,West,1/9/2024,Delivered
3,1004,Grace Eze,Laptop,Electronics,1,180000,South,1/11/2024,Delivered
4,1005,Emeka Nwosu,Phone,Electronics,2,170000,East,1/13/2024,Delivered

In [36]:
orders.describe()

         order_id   quantity         amount
count    50.00000  50.000000      50.000000
mean   1025.50000   1.680000   81396.000000
std      14.57738   0.843704   86479.748626
min    1001.00000   1.000000    6000.000000
25%    1013.25000   1.000000   19875.000000
50%    1025.50000   1.000000   43500.000000
75%    1037.75000   2.000000  113750.000000
max    1050.00000   4.000000  360000.000000

### All the records from the table

In [4]:
orders

,order_id,customer_name,product,category,quantity,amount,region,order_date,status
0,1001,Chidi Okafor,Laptop,Electronics,2,360000,South,1/5/2024,Delivered
1,1002,Amina Bello,Phone,Electronics,1,85000,North,1/7/2024,Delivered
2,1003,Tunde Adeyemi,Tablet,Electronics,3,210000,West,1/9/2024,Delivered
3,1004,Grace Eze,Laptop,Electronics,1,180000,South,1/11/2024,Delivered
4,1005,Emeka Nwosu,Phone,Electronics,2,170000,East,1/13/2024,Delivered
5,1006,Fatima Abdullahi,Wristwatch,Accessories,1,45000,North,1/15/2024,Delivered
6,1007,Kelechi Obi,Sneakers,Footwear,2,62000,East,1/17/2024,Delivered
7,1008,Ngozi Eze,Blender,Appliances,1,28000,South,1/19/2024,Delivered
8,1009,Seun Akinwale,Office Chair,Furniture,1,95000,West,1/21/2024,Delivered
9,1010,Hauwa Musa,Handbag,Accessories,2,38000,North,1/23/2024,Delivered
10,1011,Biodun Fashola,Microwave,Appliances,1,55000,West,1/25/2024,Delivered
11,1012,Chisom Eze,Earphones,Electronics,3,21000,East,1/27/2024,Delivered
12,1013,Yusuf Ibrahim,Standing Fan,Appliances,2,34000,North,1/29/2024,Delivered
13,1014,Adaeze Nwosu,Dress,Clothing,4,18000,South,2/1/2024,Delivered
14,1015,Rotimi Adesanya,Smartwatch,Electronics,1,120000,West,2/3/2024,Delivered
15,1016,Zainab Suleiman,Perfume,Beauty,2,15000,North,2/5/2024,Delivered
16,1017,Ifeanyi Okonkwo,Gaming Console,Electronics,1,250000,East,2/7/2024,Delivered
17,1018,Blessing Okafor,Hair Dryer,Beauty,1,12000,South,2/9/2024,Delivered
18,1019,Musa Garba,Dining Table,Furniture,1,145000,North,2/11/2024,Returned
19,1020,Sola Adekunle,Sneakers,Footwear,3,93000,West,2/13/2024,Delivered
20,1021,Chidinma Obi,Laptop,Electronics,1,195000,East,2/15/2024,Delivered
21,1022,Abdulrahman Yusuf,Power Bank,Electronics,2,16000,North,2/17/2024,Delivered
22,1023,Nneka Eze,Wristwatch,Accessories,1,32000,South,2/19/2024,Delivered
23,1024,Babatunde Alabi,Refrigerator,Appliances,1,310000,West,2/21/2024,Delivered
24,1025,Oluwakemi Bello,Sunglasses,Accessories,2,9500,South,2/23/2024,Delivered
25,1026,Idris Lawal,Wireless Mouse,Electronics,3,13500,North,2/25/2024,Delivered
26,1027,Chiamaka Ibe,Yoga Mat,Sports,2,11000,East,2/27/2024,Delivered
27,1028,Gbenga Adewale,Office Desk,Furniture,1,130000,West,3/1/2024,Pending
28,1029,Rukayat Bello,Mascara Set,Beauty,3,8500,North,3/3/2024,Delivered
29,1030,Nnamdi Okafor,Keyboard,Electronics,2,25000,East,3/5/2024,Delivered
30,1031,Chinwe Ugwu,Cooking Pot Set,Appliances,1,22000,South,3/7/2024,Delivered
31,1032,Usman Dantata,Phone,Electronics,1,92000,North,3/9/2024,Delivered
32,1033,Tolulope Adeyemi,Sandals,Footwear,2,14000,West,3/11/2024,Delivered
33,1034,Ebele Okonkwo,Tablet,Electronics,1,75000,East,3/13/2024,Returned
34,1035,Hakeem Salami,Dumbbell Set,Sports,1,38000,West,3/15/2024,Delivered
35,1036,Adanna Nwachukwu,Earrings,Accessories,4,6000,South,3/17/2024,Delivered
36,1037,Salisu Mohammed,Ceiling Fan,Appliances,2,48000,North,3/19/2024,Delivered
37,1038,Obiageli Eze,Skincare Kit,Beauty,1,19500,East,3/21/2024,Delivered
38,1039,Femi Ogunleye,Laptop Bag,Accessories,2,17000,West,3/23/2024,Delivered
39,1040,Aisha Abdulkadir,Smartwatch,Electronics,1,115000,North,3/25/2024,Delivered
40,1041,Chibuike Eze,Running Shoes,Footwear,2,54000,East,3/27/2024,Delivered
41,1042,Olabisi Adeola,Iron,Appliances,1,9800,West,3/29/2024,Delivered
42,1043,Rabiu Kwankwaso,Office Chair,Furniture,2,190000,North,4/1/2024,Pending
43,1044,Ifeoma Obi,Dress,Clothing,3,27000,East,4/3/2024,Delivered
44,1045,Dapo Ojo,External SSD,Electronics,1,65000,West,4/5/2024,Delivered
45,1046,Hadiza Musa,Handbag,Accessories,1,42000,North,4/7/2024,Delivered
46,1047,Chukwuemeka Nwosu,Washing Machine,Appliances,1,285000,East,4/9/2024,Delivered
47,1048,Temitope Ogundimu,Perfume,Beauty,2,23000,West,4/11/2024,Returned
48,1049,Ismaila Ture,Phone,Electronics,1,110000,North,4/13/2024,Delivered
49,1050,Adaora Okonkwo,Blender,Appliances,1,31000,South,4/15/2024,Delivered

### Display only the Order Id, Customer Name, Region and Product Column

In [5]:
orders.columns

Index(['order_id', 'customer_name', 'product', 'category', 'quantity',
       'amount', 'region', 'order_date', 'status'],
      dtype='str')

In [9]:
orders[['order_id', 'customer_name', 'region', 'product']]

    order_id      customer_name region          product
0       1001       Chidi Okafor  South           Laptop
1       1002        Amina Bello  North            Phone
2       1003      Tunde Adeyemi   West           Tablet
3       1004          Grace Eze  South           Laptop
4       1005        Emeka Nwosu   East            Phone
5       1006   Fatima Abdullahi  North       Wristwatch
6       1007        Kelechi Obi   East         Sneakers
7       1008          Ngozi Eze  South          Blender
8       1009      Seun Akinwale   West     Office Chair
9       1010         Hauwa Musa  North          Handbag
10      1011     Biodun Fashola   West        Microwave
11      1012         Chisom Eze   East        Earphones
12      1013      Yusuf Ibrahim  North     Standing Fan
13      1014       Adaeze Nwosu  South            Dress
14      1015    Rotimi Adesanya   West       Smartwatch
15      1016    Zainab Suleiman  North          Perfume
16      1017    Ifeanyi Okonkwo   East   Gaming Console
17      1018    Blessing Okafor  South       Hair Dryer
18      1019         Musa Garba  North     Dining Table
19      1020      Sola Adekunle   West         Sneakers
20      1021       Chidinma Obi   East           Laptop
21      1022  Abdulrahman Yusuf  North       Power Bank
22      1023          Nneka Eze  South       Wristwatch
23      1024    Babatunde Alabi   West     Refrigerator
24      1025    Oluwakemi Bello  South       Sunglasses
25      1026        Idris Lawal  North   Wireless Mouse
26      1027       Chiamaka Ibe   East         Yoga Mat
27      1028     Gbenga Adewale   West      Office Desk
28      1029      Rukayat Bello  North      Mascara Set
29      1030      Nnamdi Okafor   East         Keyboard
30      1031        Chinwe Ugwu  South  Cooking Pot Set
31      1032      Usman Dantata  North            Phone
32      1033   Tolulope Adeyemi   West          Sandals
33      1034      Ebele Okonkwo   East           Tablet
34      1035      Hakeem Salami   West     Dumbbell Set
35      1036   Adanna Nwachukwu  South         Earrings
36      1037    Salisu Mohammed  North      Ceiling Fan
37      1038       Obiageli Eze   East     Skincare Kit
38      1039      Femi Ogunleye   West       Laptop Bag
39      1040   Aisha Abdulkadir  North       Smartwatch
40      1041       Chibuike Eze   East    Running Shoes
41      1042     Olabisi Adeola   West             Iron
42      1043    Rabiu Kwankwaso  North     Office Chair
43      1044         Ifeoma Obi   East            Dress
44      1045           Dapo Ojo   West     External SSD
45      1046        Hadiza Musa  North          Handbag
46      1047  Chukwuemeka Nwosu   East  Washing Machine
47      1048  Temitope Ogundimu   West          Perfume
48      1049       Ismaila Ture  North            Phone
49      1050     Adaora Okonkwo  South          Blender

In [12]:
#Or

orders.loc[:,['order_id', 'customer_name', 'region', 'product']]

    order_id      customer_name region          product
0       1001       Chidi Okafor  South           Laptop
1       1002        Amina Bello  North            Phone
2       1003      Tunde Adeyemi   West           Tablet
3       1004          Grace Eze  South           Laptop
4       1005        Emeka Nwosu   East            Phone
5       1006   Fatima Abdullahi  North       Wristwatch
6       1007        Kelechi Obi   East         Sneakers
7       1008          Ngozi Eze  South          Blender
8       1009      Seun Akinwale   West     Office Chair
9       1010         Hauwa Musa  North          Handbag
10      1011     Biodun Fashola   West        Microwave
11      1012         Chisom Eze   East        Earphones
12      1013      Yusuf Ibrahim  North     Standing Fan
13      1014       Adaeze Nwosu  South            Dress
14      1015    Rotimi Adesanya   West       Smartwatch
15      1016    Zainab Suleiman  North          Perfume
16      1017    Ifeanyi Okonkwo   East   Gaming Console
17      1018    Blessing Okafor  South       Hair Dryer
18      1019         Musa Garba  North     Dining Table
19      1020      Sola Adekunle   West         Sneakers
20      1021       Chidinma Obi   East           Laptop
21      1022  Abdulrahman Yusuf  North       Power Bank
22      1023          Nneka Eze  South       Wristwatch
23      1024    Babatunde Alabi   West     Refrigerator
24      1025    Oluwakemi Bello  South       Sunglasses
25      1026        Idris Lawal  North   Wireless Mouse
26      1027       Chiamaka Ibe   East         Yoga Mat
27      1028     Gbenga Adewale   West      Office Desk
28      1029      Rukayat Bello  North      Mascara Set
29      1030      Nnamdi Okafor   East         Keyboard
30      1031        Chinwe Ugwu  South  Cooking Pot Set
31      1032      Usman Dantata  North            Phone
32      1033   Tolulope Adeyemi   West          Sandals
33      1034      Ebele Okonkwo   East           Tablet
34      1035      Hakeem Salami   West     Dumbbell Set
35      1036   Adanna Nwachukwu  South         Earrings
36      1037    Salisu Mohammed  North      Ceiling Fan
37      1038       Obiageli Eze   East     Skincare Kit
38      1039      Femi Ogunleye   West       Laptop Bag
39      1040   Aisha Abdulkadir  North       Smartwatch
40      1041       Chibuike Eze   East    Running Shoes
41      1042     Olabisi Adeola   West             Iron
42      1043    Rabiu Kwankwaso  North     Office Chair
43      1044         Ifeoma Obi   East            Dress
44      1045           Dapo Ojo   West     External SSD
45      1046        Hadiza Musa  North          Handbag
46      1047  Chukwuemeka Nwosu   East  Washing Machine
47      1048  Temitope Ogundimu   West          Perfume
48      1049       Ismaila Ture  North            Phone
49      1050     Adaora Okonkwo  South          Blender

### Retrieve all orders where Total Amount is greater than 100,000

In [13]:
orders.columns

Index(['order_id', 'customer_name', 'product', 'category', 'quantity',
       'amount', 'region', 'order_date', 'status'],
      dtype='str')

In [15]:
orders[orders['amount'] > 100000]

,order_id,customer_name,product,category,quantity,amount,region,order_date,status
0,1001,Chidi Okafor,Laptop,Electronics,2,360000,South,1/5/2024,Delivered
2,1003,Tunde Adeyemi,Tablet,Electronics,3,210000,West,1/9/2024,Delivered
3,1004,Grace Eze,Laptop,Electronics,1,180000,South,1/11/2024,Delivered
4,1005,Emeka Nwosu,Phone,Electronics,2,170000,East,1/13/2024,Delivered
14,1015,Rotimi Adesanya,Smartwatch,Electronics,1,120000,West,2/3/2024,Delivered
16,1017,Ifeanyi Okonkwo,Gaming Console,Electronics,1,250000,East,2/7/2024,Delivered
18,1019,Musa Garba,Dining Table,Furniture,1,145000,North,2/11/2024,Returned
20,1021,Chidinma Obi,Laptop,Electronics,1,195000,East,2/15/2024,Delivered
23,1024,Babatunde Alabi,Refrigerator,Appliances,1,310000,West,2/21/2024,Delivered
27,1028,Gbenga Adewale,Office Desk,Furniture,1,130000,West,3/1/2024,Pending
39,1040,Aisha Abdulkadir,Smartwatch,Electronics,1,115000,North,3/25/2024,Delivered
42,1043,Rabiu Kwankwaso,Office Chair,Furniture,2,190000,North,4/1/2024,Pending
46,1047,Chukwuemeka Nwosu,Washing Machine,Appliances,1,285000,East,4/9/2024,Delivered
48,1049,Ismaila Ture,Phone,Electronics,1,110000,North,4/13/2024,Delivered

### Display only Customers in the Eastern Region

In [17]:
orders[orders['region'] == 'East']

,order_id,customer_name,product,category,quantity,amount,region,order_date,status
4,1005,Emeka Nwosu,Phone,Electronics,2,170000,East,1/13/2024,Delivered
6,1007,Kelechi Obi,Sneakers,Footwear,2,62000,East,1/17/2024,Delivered
11,1012,Chisom Eze,Earphones,Electronics,3,21000,East,1/27/2024,Delivered
16,1017,Ifeanyi Okonkwo,Gaming Console,Electronics,1,250000,East,2/7/2024,Delivered
20,1021,Chidinma Obi,Laptop,Electronics,1,195000,East,2/15/2024,Delivered
26,1027,Chiamaka Ibe,Yoga Mat,Sports,2,11000,East,2/27/2024,Delivered
29,1030,Nnamdi Okafor,Keyboard,Electronics,2,25000,East,3/5/2024,Delivered
33,1034,Ebele Okonkwo,Tablet,Electronics,1,75000,East,3/13/2024,Returned
37,1038,Obiageli Eze,Skincare Kit,Beauty,1,19500,East,3/21/2024,Delivered
40,1041,Chibuike Eze,Running Shoes,Footwear,2,54000,East,3/27/2024,Delivered
43,1044,Ifeoma Obi,Dress,Clothing,3,27000,East,4/3/2024,Delivered
46,1047,Chukwuemeka Nwosu,Washing Machine,Appliances,1,285000,East,4/9/2024,Delivered

### Display the top region by the average amount and sort the result in decending order

In [21]:
orders.groupby('region')['amount'].mean().sort_values(ascending=False)

region
East     99541.666667
West     90753.846154
South    69850.000000
North    66466.666667
Name: amount, dtype: float64

In [22]:
# Or

In [33]:
dataframe = (orders.groupby('region', as_index=False)['amount'].mean().sort_values('amount', ascending=False))

In [34]:
dataframe

  region        amount
0   East  99541.666667
3   West  90753.846154
2  South  69850.000000
1  North  66466.666667